// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func NavBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"bg-slate-900 fixed top-0 left-0 right-0 z-50\"><nav class=\"mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8\" aria-label=\"Global\"><div class=\"hidden lg:flex lg:gap-x-12 ml-auto\"><div class=\"relative\"><button type=\"button\" class=\"flex items-center gap-x-1 text-sm font-semibold leading-6 text-gray-300 link-underline link-underline-black\" hx-get=\"/about\" hx-swap=\"innerHTML\" hx-target=\"#main-content\" hx-trigger=\"click\">About Me    </button></div><div class=\"relative\"><button type=\"button\" class=\"flex items-center gap-x-1 text-sm font-semibold leading-6 text-gray-300 link-underline link-underline-black\" hx-get=\"/projects\" hx-swap=\"innerHTML\" hx-target=\"#main-content\" hx-trigger=\"click\">Projects </button></div><div class=\"relative\"><button type=\"button\" class=\"flex items-center gap-x-1 text-sm font-semibold leading-6 text-gray-300 link-underline link-underline-black\" hx-get=\"/contact\" hx-swap=\"innerHTML\" hx-target=\"#main-content\" hx-trigger=\"click\">Contact</button></div></div></nav></header><style>\n\t.link-underline {\n\t\tborder-bottom-width: 0;\n\t\tbackground-image: linear-gradient(transparent, transparent), linear-gradient(#fff, #fff);\n\t\tbackground-size: 0 3px;\n\t\tbackground-position: 0 100%;\n\t\tbackground-repeat: no-repeat;\n\t\ttransition: background-size .25s ease-in-out;\n\t}\n\n\t.link-underline-black {\n\t\tbackground-image: linear-gradient(transparent, transparent), linear-gradient(#059669, #059669)\n\t}\n\n\t.link-underline:hover {\n\t\tbackground-size: 100% 3px;\n\t\tbackground-position: 0 100%\n\t}\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
