// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Portfolio() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-black h-screen w-screen flex flex-col pt-[250px] pl-[150px] gap-[10px]\"><div class=\"flex flex-row\"><span>👋</span><h1 class=\"text-white font-medium pb-[17px] text-gray-500\">Hi!\r</h1></div><p class=\"font-sans text-white text-5xl whitespace-pre-line\">I am an aspiring <span class=\"font-serif\">Full-stack Software Engineer</span>;\r</p><p class=\"font-sans text-white text-5xl whitespace-pre-line\">currently studying <span class=\"font-serif\">Computer Engineering</span> and <span class=\"font-serif\">Math</span></p><p class=\"font-sans text-white text-5xl whitespace-pre-line pb-[25px]\">at <span class=\"font-serif\">Northwestern University</span>.\r</p><p class=\"w-5/12 text-gray-500 pb-[25px]\">I have had the opportunity to be involved in a variety of projects spanning machine learning, artificial intelligence, full-stack development, and systems engineering.\r</p><p class=\"text-gray-500\">References - Juxta, GPT-Page-Finder, Auctus\r</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
