// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Portfolio() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<head><style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n        header {\r\n            background-color: #333;\r\n            color: #fff;\r\n            padding: 20px;\r\n            text-align: center;\r\n        }\r\n        nav {\r\n            background-color: #444;\r\n            padding: 10px 0;\r\n            text-align: center;\r\n        }\r\n        nav a {\r\n            color: #fff;\r\n            text-decoration: none;\r\n            padding: 0 20px;\r\n        }\r\n        nav a:hover {\r\n            color: #ccc;\r\n        }\r\n        section {\r\n            padding: 20px;\r\n            text-align: center;\r\n        }\r\n        footer {\r\n            background-color: #333;\r\n            color: #fff;\r\n            text-align: center;\r\n            padding: 20px;\r\n            position: fixed;\r\n            bottom: 0;\r\n            width: 100%;\r\n        }\r\n    </style></head><div><header><h1>My Portfolio</h1></header><nav><a href=\"#about\">About Me</a> <a href=\"#projects\">Projects</a> <a href=\"#contact\">Contact</a></nav><section id=\"about\"><h2>About Me</h2><p>Welcome to my portfolio website. I'm passionate about web development and design.</p></section><section id=\"projects\"><h2>Projects</h2><p>Here are some of the projects I've worked on:</p><ul><li>Project 1</li><li>Project 2</li><li>Project 3</li></ul></section><section id=\"contact\"><h2>Contact</h2><p>You can reach me at: email@example.com</p></section><footer>&copy; 2024 My Portfolio\r</footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
